<?php

declare(strict_types=1);

namespace Kalle\Pdf\Font;

final class StandardFontWesternGlyphMap
{
    /**
     * @var array<string, string>
     */
    public const MAP = [
        '¡' => 'exclamdown',
        '¢' => 'cent',
        '£' => 'sterling',
        '¤' => 'currency',
        '¥' => 'yen',
        '¦' => 'brokenbar',
        '§' => 'section',
        '¨' => 'dieresis',
        '©' => 'copyright',
        'ª' => 'ordfeminine',
        '«' => 'guillemotleft',
        '¬' => 'logicalnot',
        '®' => 'registered',
        '¯' => 'macron',
        '°' => 'degree',
        '±' => 'plusminus',
        '²' => 'twosuperior',
        '³' => 'threesuperior',
        '´' => 'acute',
        'µ' => 'mu',
        '¶' => 'paragraph',
        '·' => 'periodcentered',
        '¸' => 'cedilla',
        '¹' => 'onesuperior',
        'º' => 'ordmasculine',
        '»' => 'guillemotright',
        '¼' => 'onequarter',
        '½' => 'onehalf',
        '¾' => 'threequarters',
        '¿' => 'questiondown',
        'À' => 'Agrave',
        'Á' => 'Aacute',
        'Â' => 'Acircumflex',
        'Ã' => 'Atilde',
        'Ä' => 'Adieresis',
        'Å' => 'Aring',
        'Æ' => 'AE',
        'Ç' => 'Ccedilla',
        'È' => 'Egrave',
        'É' => 'Eacute',
        'Ê' => 'Ecircumflex',
        'Ë' => 'Edieresis',
        'Ì' => 'Igrave',
        'Í' => 'Iacute',
        'Î' => 'Icircumflex',
        'Ï' => 'Idieresis',
        'Ð' => 'Eth',
        'Ñ' => 'Ntilde',
        'Ò' => 'Ograve',
        'Ó' => 'Oacute',
        'Ô' => 'Ocircumflex',
        'Õ' => 'Otilde',
        'Ö' => 'Odieresis',
        '×' => 'multiply',
        'Ø' => 'Oslash',
        'Ù' => 'Ugrave',
        'Ú' => 'Uacute',
        'Û' => 'Ucircumflex',
        'Ü' => 'Udieresis',
        'Ý' => 'Yacute',
        'Þ' => 'Thorn',
        'ß' => 'germandbls',
        'à' => 'agrave',
        'á' => 'aacute',
        'â' => 'acircumflex',
        'ã' => 'atilde',
        'ä' => 'adieresis',
        'å' => 'aring',
        'æ' => 'ae',
        'ç' => 'ccedilla',
        'è' => 'egrave',
        'é' => 'eacute',
        'ê' => 'ecircumflex',
        'ë' => 'edieresis',
        'ì' => 'igrave',
        'í' => 'iacute',
        'î' => 'icircumflex',
        'ï' => 'idieresis',
        'ð' => 'eth',
        'ñ' => 'ntilde',
        'ò' => 'ograve',
        'ó' => 'oacute',
        'ô' => 'ocircumflex',
        'õ' => 'otilde',
        'ö' => 'odieresis',
        '÷' => 'divide',
        'ø' => 'oslash',
        'ù' => 'ugrave',
        'ú' => 'uacute',
        'û' => 'ucircumflex',
        'ü' => 'udieresis',
        'ý' => 'yacute',
        'þ' => 'thorn',
        'ÿ' => 'ydieresis',
        'Œ' => 'OE',
        'œ' => 'oe',
        'Š' => 'Scaron',
        'š' => 'scaron',
        'Ÿ' => 'Ydieresis',
        'Ž' => 'Zcaron',
        'ž' => 'zcaron',
        'ƒ' => 'florin',
        'ˆ' => 'circumflex',
        '˜' => 'tilde',
        '–' => 'endash',
        '—' => 'emdash',
        '‘' => 'quoteleft',
        '’' => 'quoteright',
        '‚' => 'quotesinglbase',
        '“' => 'quotedblleft',
        '”' => 'quotedblright',
        '„' => 'quotedblbase',
        '†' => 'dagger',
        '‡' => 'daggerdbl',
        '•' => 'bullet',
        '…' => 'ellipsis',
        '‰' => 'perthousand',
        '‹' => 'guilsinglleft',
        '›' => 'guilsinglright',
        '€' => 'Euro',
        '™' => 'trademark'
    ];

    public static function glyphName(string $character): ?string
    {
        return self::MAP[$character] ?? null;
    }
}
